name: Java CI with Maven in Linux

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: xvfb-run mvn verify -Pdocker,jacoco,coveralls,mutation-testing
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Sonar Cloud report
      if: ${{ env.SONAR_TOKEN }}
      run: mvn sonar:sonar -Psonarcloud
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Junit report
      run: mvn surefire-report:report-only
      if: ${{ always() }}
    - name: Archive Junit report
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: surefire-report
        path: '**/target/surefire-reports'
    - name: Archive Jacoco report
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: jacoco-report
        path: ./target/site/jacoco
    - name: Archive Pit Report
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: pit-report
        path: ./target/pit-reports